module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/previews/{{bundle.inputData.preview}}',
      method: 'GET',
      params: {},
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: { preview: '{{bundle.inputData.preview}}' },
      removeMissingValuesFrom: {},
    },
    inputFields: [
      {
        key: 'preview',
        label: 'Preview ID',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      anchor: false,
      anchor_type: 'all',
      base: '5d9b59f952163c73a0508bb5',
      build_begin: '2019-10-07T18:29:55.631Z',
      build_end: '2019-10-07T18:30:18.664Z',
      children: ['5d9b842252163ca8a1508c11'],
      clone: '5d9b842252163ca8a1508c11',
      createdAt: '2019-10-07T18:29:54.123Z',
      config: {
        services: {
          property1: {
            alias_type: 'default',
            aliases: ['foo', 'bar'],
            checkout: true,
            checkout_path: '/var/lib/tugboat',
            commands: {
              init: [
                'a2enmod headers rewrite',
                'ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"',
              ],
              update: [
                'cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/"',
              ],
              build: [
                'drush -r "${DOCROOT}" cache-clear all',
                'drush -r "${DOCROOT}" updb -y',
              ],
              ready: ['string'],
              online: ['curl -LI http://localhost'],
              start: ['touch /tmp/controlfile'],
              clone: [
                'ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}/${TUGBOAT_PREVIEW_ID}"',
              ],
            },
            default: true,
            depends: ['mysql'],
            domain: 'example.com',
            expose: 80,
            http: false,
            https: true,
            image: 'tugboatqa/httpd:2.4',
            subpath: false,
            subpath_map: true,
            visualdiffs: [
              {
                aliases: [':default'],
                fullPage: true,
                timeout: 30,
                url: '/about',
                waitUntil: [['load']],
              },
            ],
          },
          property2: {
            alias_type: 'default',
            aliases: ['foo', 'bar'],
            checkout: true,
            checkout_path: '/var/lib/tugboat',
            commands: {
              init: [
                'a2enmod headers rewrite',
                'ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"',
              ],
              update: [
                'cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/"',
              ],
              build: [
                'drush -r "${DOCROOT}" cache-clear all',
                'drush -r "${DOCROOT}" updb -y',
              ],
              ready: ['string'],
              online: ['curl -LI http://localhost'],
              start: ['touch /tmp/controlfile'],
              clone: [
                'ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}/${TUGBOAT_PREVIEW_ID}"',
              ],
            },
            default: true,
            depends: ['mysql'],
            domain: 'example.com',
            expose: 80,
            http: false,
            https: true,
            image: 'tugboatqa/httpd:2.4',
            subpath: false,
            subpath_map: true,
            visualdiffs: [
              {
                aliases: [':default'],
                fullPage: true,
                timeout: 30,
                url: '/about',
                waitUntil: [['load']],
              },
            ],
          },
        },
      },
      default_service: '5d9b842352163cc294508c15',
      expires: '2019-10-07T18:30:18.664Z',
      failed: 'ready',
      hits: 1234,
      id: '5d9b842252163ca8a1508c11',
      job: '5d9e0a3f7f02ad896974a975',
      lasthit: '2019-10-07T20:09:13.330Z',
      locked: false,
      mail: ['5d9b842d52163c3f95508c26'],
      name: 'string',
      orphaned: '5d9b842252163ca8a1508c11',
      preview: '5d9b842252163ca8a1508c11',
      project: '5d810c19f6f8203d5b65ef01',
      provider: 'bitbucket',
      provider_comment: 12345,
      provider_id: 'string',
      provider_label: 'string',
      provider_link: 'http://example.com',
      provider_link_sha: 'http://example.com',
      provider_ref: {},
      provider_type: 'branch',
      repo: '5d810c19f6f82083ed65ef03',
      services: ['5d9b842352163cc294508c15'],
      ref: 'pr123',
      sha: 'aa5db6479307593d10257ee03256f47f2abfdf8a',
      size: 1921191078,
      stale: false,
      state: 'ready',
      suspended: 'ready',
      type: 'preview',
      updatedAt: '2019-10-07T20:30:11.933Z',
      url: 'https://pr123-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
      urls: [
        'https://pr123-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
        'https://foo-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
        'https://bar-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
      ],
      visualdiffs: false,
    },
    outputFields: [
      { key: 'anchor', type: 'boolean' },
      { key: 'anchor_type' },
      { key: 'base' },
      { key: 'build_begin', type: 'datetime' },
      { key: 'build_end', type: 'datetime' },
      { key: 'children[]0' },
      { key: 'children[]1' },
      { key: 'children[]2' },
      { key: 'children[]3' },
      { key: 'children[]4' },
      { key: 'children[]5' },
      { key: 'children[]6' },
      { key: 'children[]7' },
      { key: 'children[]8' },
      { key: 'children[]9' },
      { key: 'children[]10' },
      { key: 'children[]11' },
      { key: 'children[]12' },
      { key: 'children[]13' },
      { key: 'children[]14' },
      { key: 'children[]15' },
      { key: 'children[]16' },
      { key: 'children[]17' },
      { key: 'children[]18' },
      { key: 'children[]19' },
      { key: 'children[]20' },
      { key: 'children[]21' },
      { key: 'children[]22' },
      { key: 'children[]23' },
      { key: 'clone' },
      { key: 'createdAt', type: 'datetime' },
      { key: 'config__services__property1__alias_type' },
      { key: 'config__services__property1__aliases[]0' },
      { key: 'config__services__property1__aliases[]1' },
      { key: 'config__services__property1__aliases[]2' },
      { key: 'config__services__property1__checkout' },
      { key: 'config__services__property1__checkout_path' },
      { key: 'config__services__property1__commands__init[]0' },
      { key: 'config__services__property1__commands__init[]1' },
      { key: 'config__services__property1__commands__init[]2' },
      { key: 'config__services__property1__commands__init[]3' },
      { key: 'config__services__property1__commands__init[]4' },
      { key: 'config__services__property1__commands__init[]5' },
      { key: 'config__services__property1__commands__init[]6' },
      { key: 'config__services__property1__commands__init[]7' },
      { key: 'config__services__property1__commands__init[]8' },
      { key: 'config__services__property1__commands__init[]9' },
      { key: 'config__services__property1__commands__init[]10' },
      { key: 'config__services__property1__commands__init[]11' },
      { key: 'config__services__property1__commands__init[]12' },
      { key: 'config__services__property1__commands__init[]13' },
      { key: 'config__services__property1__commands__init[]14' },
      { key: 'config__services__property1__commands__init[]15' },
      { key: 'config__services__property1__commands__init[]16' },
      { key: 'config__services__property1__commands__init[]17' },
      { key: 'config__services__property1__commands__init[]18' },
      { key: 'config__services__property1__commands__init[]19' },
      { key: 'config__services__property1__commands__init[]20' },
      { key: 'config__services__property1__commands__init[]21' },
      { key: 'config__services__property1__commands__init[]22' },
      { key: 'config__services__property1__commands__init[]23' },
      { key: 'config__services__property1__commands__init[]24' },
      { key: 'config__services__property1__commands__init[]25' },
      { key: 'config__services__property1__commands__init[]26' },
      { key: 'config__services__property1__commands__init[]27' },
      { key: 'config__services__property1__commands__init[]28' },
      { key: 'config__services__property1__commands__init[]29' },
      { key: 'config__services__property1__commands__init[]30' },
      { key: 'config__services__property1__commands__init[]31' },
      { key: 'config__services__property1__commands__init[]32' },
      { key: 'config__services__property1__commands__init[]33' },
      { key: 'config__services__property1__commands__init[]34' },
      { key: 'config__services__property1__commands__init[]35' },
      { key: 'config__services__property1__commands__init[]36' },
      { key: 'config__services__property1__commands__init[]37' },
      { key: 'config__services__property1__commands__init[]38' },
      { key: 'config__services__property1__commands__init[]39' },
      { key: 'config__services__property1__commands__init[]40' },
      { key: 'config__services__property1__commands__init[]41' },
      { key: 'config__services__property1__commands__init[]42' },
      { key: 'config__services__property1__commands__init[]43' },
      { key: 'config__services__property1__commands__init[]44' },
      { key: 'config__services__property1__commands__init[]45' },
      { key: 'config__services__property1__commands__update[]0' },
      { key: 'config__services__property1__commands__update[]1' },
      { key: 'config__services__property1__commands__update[]2' },
      { key: 'config__services__property1__commands__update[]3' },
      { key: 'config__services__property1__commands__update[]4' },
      { key: 'config__services__property1__commands__update[]5' },
      { key: 'config__services__property1__commands__update[]6' },
      { key: 'config__services__property1__commands__update[]7' },
      { key: 'config__services__property1__commands__update[]8' },
      { key: 'config__services__property1__commands__update[]9' },
      { key: 'config__services__property1__commands__update[]10' },
      { key: 'config__services__property1__commands__update[]11' },
      { key: 'config__services__property1__commands__update[]12' },
      { key: 'config__services__property1__commands__update[]13' },
      { key: 'config__services__property1__commands__update[]14' },
      { key: 'config__services__property1__commands__update[]15' },
      { key: 'config__services__property1__commands__update[]16' },
      { key: 'config__services__property1__commands__update[]17' },
      { key: 'config__services__property1__commands__update[]18' },
      { key: 'config__services__property1__commands__update[]19' },
      { key: 'config__services__property1__commands__update[]20' },
      { key: 'config__services__property1__commands__update[]21' },
      { key: 'config__services__property1__commands__update[]22' },
      { key: 'config__services__property1__commands__update[]23' },
      { key: 'config__services__property1__commands__update[]24' },
      { key: 'config__services__property1__commands__update[]25' },
      { key: 'config__services__property1__commands__update[]26' },
      { key: 'config__services__property1__commands__update[]27' },
      { key: 'config__services__property1__commands__update[]28' },
      { key: 'config__services__property1__commands__update[]29' },
      { key: 'config__services__property1__commands__update[]30' },
      { key: 'config__services__property1__commands__update[]31' },
      { key: 'config__services__property1__commands__update[]32' },
      { key: 'config__services__property1__commands__update[]33' },
      { key: 'config__services__property1__commands__update[]34' },
      { key: 'config__services__property1__commands__update[]35' },
      { key: 'config__services__property1__commands__update[]36' },
      { key: 'config__services__property1__commands__update[]37' },
      { key: 'config__services__property1__commands__update[]38' },
      { key: 'config__services__property1__commands__update[]39' },
      { key: 'config__services__property1__commands__update[]40' },
      { key: 'config__services__property1__commands__update[]41' },
      { key: 'config__services__property1__commands__update[]42' },
      { key: 'config__services__property1__commands__update[]43' },
      { key: 'config__services__property1__commands__update[]44' },
      { key: 'config__services__property1__commands__update[]45' },
      { key: 'config__services__property1__commands__update[]46' },
      { key: 'config__services__property1__commands__update[]47' },
      { key: 'config__services__property1__commands__update[]48' },
      { key: 'config__services__property1__commands__update[]49' },
      { key: 'config__services__property1__commands__update[]50' },
      { key: 'config__services__property1__commands__update[]51' },
      { key: 'config__services__property1__commands__update[]52' },
      { key: 'config__services__property1__commands__update[]53' },
      { key: 'config__services__property1__commands__update[]54' },
      { key: 'config__services__property1__commands__update[]55' },
      { key: 'config__services__property1__commands__update[]56' },
      { key: 'config__services__property1__commands__update[]57' },
      { key: 'config__services__property1__commands__update[]58' },
      { key: 'config__services__property1__commands__update[]59' },
      { key: 'config__services__property1__commands__update[]60' },
      { key: 'config__services__property1__commands__update[]61' },
      { key: 'config__services__property1__commands__update[]62' },
      { key: 'config__services__property1__commands__update[]63' },
      { key: 'config__services__property1__commands__update[]64' },
      { key: 'config__services__property1__commands__update[]65' },
      { key: 'config__services__property1__commands__update[]66' },
      { key: 'config__services__property1__commands__update[]67' },
      { key: 'config__services__property1__commands__update[]68' },
      { key: 'config__services__property1__commands__update[]69' },
      { key: 'config__services__property1__commands__update[]70' },
      { key: 'config__services__property1__commands__update[]71' },
      { key: 'config__services__property1__commands__update[]72' },
      { key: 'config__services__property1__commands__update[]73' },
      { key: 'config__services__property1__commands__update[]74' },
      { key: 'config__services__property1__commands__update[]75' },
      { key: 'config__services__property1__commands__build[]0' },
      { key: 'config__services__property1__commands__build[]1' },
      { key: 'config__services__property1__commands__build[]2' },
      { key: 'config__services__property1__commands__build[]3' },
      { key: 'config__services__property1__commands__build[]4' },
      { key: 'config__services__property1__commands__build[]5' },
      { key: 'config__services__property1__commands__build[]6' },
      { key: 'config__services__property1__commands__build[]7' },
      { key: 'config__services__property1__commands__build[]8' },
      { key: 'config__services__property1__commands__build[]9' },
      { key: 'config__services__property1__commands__build[]10' },
      { key: 'config__services__property1__commands__build[]11' },
      { key: 'config__services__property1__commands__build[]12' },
      { key: 'config__services__property1__commands__build[]13' },
      { key: 'config__services__property1__commands__build[]14' },
      { key: 'config__services__property1__commands__build[]15' },
      { key: 'config__services__property1__commands__build[]16' },
      { key: 'config__services__property1__commands__build[]17' },
      { key: 'config__services__property1__commands__build[]18' },
      { key: 'config__services__property1__commands__build[]19' },
      { key: 'config__services__property1__commands__build[]20' },
      { key: 'config__services__property1__commands__build[]21' },
      { key: 'config__services__property1__commands__build[]22' },
      { key: 'config__services__property1__commands__build[]23' },
      { key: 'config__services__property1__commands__build[]24' },
      { key: 'config__services__property1__commands__build[]25' },
      { key: 'config__services__property1__commands__build[]26' },
      { key: 'config__services__property1__commands__build[]27' },
      { key: 'config__services__property1__commands__build[]28' },
      { key: 'config__services__property1__commands__build[]29' },
      { key: 'config__services__property1__commands__build[]30' },
      { key: 'config__services__property1__commands__build[]31' },
      { key: 'config__services__property1__commands__build[]32' },
      { key: 'config__services__property1__commands__build[]33' },
      { key: 'config__services__property1__commands__build[]34' },
      { key: 'config__services__property1__commands__build[]35' },
      { key: 'config__services__property1__commands__build[]36' },
      { key: 'config__services__property1__commands__ready[]0' },
      { key: 'config__services__property1__commands__ready[]1' },
      { key: 'config__services__property1__commands__ready[]2' },
      { key: 'config__services__property1__commands__ready[]3' },
      { key: 'config__services__property1__commands__ready[]4' },
      { key: 'config__services__property1__commands__ready[]5' },
      { key: 'config__services__property1__commands__online[]0' },
      { key: 'config__services__property1__commands__online[]1' },
      { key: 'config__services__property1__commands__online[]2' },
      { key: 'config__services__property1__commands__online[]3' },
      { key: 'config__services__property1__commands__online[]4' },
      { key: 'config__services__property1__commands__online[]5' },
      { key: 'config__services__property1__commands__online[]6' },
      { key: 'config__services__property1__commands__online[]7' },
      { key: 'config__services__property1__commands__online[]8' },
      { key: 'config__services__property1__commands__online[]9' },
      { key: 'config__services__property1__commands__online[]10' },
      { key: 'config__services__property1__commands__online[]11' },
      { key: 'config__services__property1__commands__online[]12' },
      { key: 'config__services__property1__commands__online[]13' },
      { key: 'config__services__property1__commands__online[]14' },
      { key: 'config__services__property1__commands__online[]15' },
      { key: 'config__services__property1__commands__online[]16' },
      { key: 'config__services__property1__commands__online[]17' },
      { key: 'config__services__property1__commands__online[]18' },
      { key: 'config__services__property1__commands__online[]19' },
      { key: 'config__services__property1__commands__online[]20' },
      { key: 'config__services__property1__commands__online[]21' },
      { key: 'config__services__property1__commands__online[]22' },
      { key: 'config__services__property1__commands__online[]23' },
      { key: 'config__services__property1__commands__online[]24' },
      { key: 'config__services__property1__commands__start[]0' },
      { key: 'config__services__property1__commands__start[]1' },
      { key: 'config__services__property1__commands__start[]2' },
      { key: 'config__services__property1__commands__start[]3' },
      { key: 'config__services__property1__commands__start[]4' },
      { key: 'config__services__property1__commands__start[]5' },
      { key: 'config__services__property1__commands__start[]6' },
      { key: 'config__services__property1__commands__start[]7' },
      { key: 'config__services__property1__commands__start[]8' },
      { key: 'config__services__property1__commands__start[]9' },
      { key: 'config__services__property1__commands__start[]10' },
      { key: 'config__services__property1__commands__start[]11' },
      { key: 'config__services__property1__commands__start[]12' },
      { key: 'config__services__property1__commands__start[]13' },
      { key: 'config__services__property1__commands__start[]14' },
      { key: 'config__services__property1__commands__start[]15' },
      { key: 'config__services__property1__commands__start[]16' },
      { key: 'config__services__property1__commands__start[]17' },
      { key: 'config__services__property1__commands__start[]18' },
      { key: 'config__services__property1__commands__start[]19' },
      { key: 'config__services__property1__commands__start[]20' },
      { key: 'config__services__property1__commands__start[]21' },
      { key: 'config__services__property1__commands__clone[]0' },
      { key: 'config__services__property1__commands__clone[]1' },
      { key: 'config__services__property1__commands__clone[]2' },
      { key: 'config__services__property1__commands__clone[]3' },
      { key: 'config__services__property1__commands__clone[]4' },
      { key: 'config__services__property1__commands__clone[]5' },
      { key: 'config__services__property1__commands__clone[]6' },
      { key: 'config__services__property1__commands__clone[]7' },
      { key: 'config__services__property1__commands__clone[]8' },
      { key: 'config__services__property1__commands__clone[]9' },
      { key: 'config__services__property1__commands__clone[]10' },
      { key: 'config__services__property1__commands__clone[]11' },
      { key: 'config__services__property1__commands__clone[]12' },
      { key: 'config__services__property1__commands__clone[]13' },
      { key: 'config__services__property1__commands__clone[]14' },
      { key: 'config__services__property1__commands__clone[]15' },
      { key: 'config__services__property1__commands__clone[]16' },
      { key: 'config__services__property1__commands__clone[]17' },
      { key: 'config__services__property1__commands__clone[]18' },
      { key: 'config__services__property1__commands__clone[]19' },
      { key: 'config__services__property1__commands__clone[]20' },
      { key: 'config__services__property1__commands__clone[]21' },
      { key: 'config__services__property1__commands__clone[]22' },
      { key: 'config__services__property1__commands__clone[]23' },
      { key: 'config__services__property1__commands__clone[]24' },
      { key: 'config__services__property1__commands__clone[]25' },
      { key: 'config__services__property1__commands__clone[]26' },
      { key: 'config__services__property1__commands__clone[]27' },
      { key: 'config__services__property1__commands__clone[]28' },
      { key: 'config__services__property1__commands__clone[]29' },
      { key: 'config__services__property1__commands__clone[]30' },
      { key: 'config__services__property1__commands__clone[]31' },
      { key: 'config__services__property1__commands__clone[]32' },
      { key: 'config__services__property1__commands__clone[]33' },
      { key: 'config__services__property1__commands__clone[]34' },
      { key: 'config__services__property1__commands__clone[]35' },
      { key: 'config__services__property1__commands__clone[]36' },
      { key: 'config__services__property1__commands__clone[]37' },
      { key: 'config__services__property1__commands__clone[]38' },
      { key: 'config__services__property1__commands__clone[]39' },
      { key: 'config__services__property1__commands__clone[]40' },
      { key: 'config__services__property1__commands__clone[]41' },
      { key: 'config__services__property1__commands__clone[]42' },
      { key: 'config__services__property1__commands__clone[]43' },
      { key: 'config__services__property1__commands__clone[]44' },
      { key: 'config__services__property1__commands__clone[]45' },
      { key: 'config__services__property1__commands__clone[]46' },
      { key: 'config__services__property1__commands__clone[]47' },
      { key: 'config__services__property1__commands__clone[]48' },
      { key: 'config__services__property1__commands__clone[]49' },
      { key: 'config__services__property1__commands__clone[]50' },
      { key: 'config__services__property1__commands__clone[]51' },
      { key: 'config__services__property1__commands__clone[]52' },
      { key: 'config__services__property1__commands__clone[]53' },
      { key: 'config__services__property1__commands__clone[]54' },
      { key: 'config__services__property1__commands__clone[]55' },
      { key: 'config__services__property1__commands__clone[]56' },
      { key: 'config__services__property1__commands__clone[]57' },
      { key: 'config__services__property1__commands__clone[]58' },
      { key: 'config__services__property1__commands__clone[]59' },
      { key: 'config__services__property1__default' },
      { key: 'config__services__property1__depends[]0' },
      { key: 'config__services__property1__depends[]1' },
      { key: 'config__services__property1__depends[]2' },
      { key: 'config__services__property1__depends[]3' },
      { key: 'config__services__property1__depends[]4' },
      { key: 'config__services__property1__domain' },
      { key: 'config__services__property1__expose' },
      { key: 'config__services__property1__http' },
      { key: 'config__services__property1__https' },
      { key: 'config__services__property1__image' },
      { key: 'config__services__property1__subpath' },
      { key: 'config__services__property1__subpath_map' },
      { key: 'config__services__property1__visualdiffs[]aliases[]0' },
      { key: 'config__services__property1__visualdiffs[]aliases[]1' },
      { key: 'config__services__property1__visualdiffs[]aliases[]2' },
      { key: 'config__services__property1__visualdiffs[]aliases[]3' },
      { key: 'config__services__property1__visualdiffs[]aliases[]4' },
      { key: 'config__services__property1__visualdiffs[]aliases[]5' },
      { key: 'config__services__property1__visualdiffs[]aliases[]6' },
      { key: 'config__services__property1__visualdiffs[]aliases[]7' },
      { key: 'config__services__property1__visualdiffs[]fullPage' },
      { key: 'config__services__property1__visualdiffs[]timeout' },
      { key: 'config__services__property1__visualdiffs[]url' },
      { key: 'config__services__property1__visualdiffs[]waitUntil[]0' },
      { key: 'config__services__property2__alias_type' },
      { key: 'config__services__property2__aliases[]0' },
      { key: 'config__services__property2__aliases[]1' },
      { key: 'config__services__property2__aliases[]2' },
      { key: 'config__services__property2__checkout' },
      { key: 'config__services__property2__checkout_path' },
      { key: 'config__services__property2__commands__init[]0' },
      { key: 'config__services__property2__commands__init[]1' },
      { key: 'config__services__property2__commands__init[]2' },
      { key: 'config__services__property2__commands__init[]3' },
      { key: 'config__services__property2__commands__init[]4' },
      { key: 'config__services__property2__commands__init[]5' },
      { key: 'config__services__property2__commands__init[]6' },
      { key: 'config__services__property2__commands__init[]7' },
      { key: 'config__services__property2__commands__init[]8' },
      { key: 'config__services__property2__commands__init[]9' },
      { key: 'config__services__property2__commands__init[]10' },
      { key: 'config__services__property2__commands__init[]11' },
      { key: 'config__services__property2__commands__init[]12' },
      { key: 'config__services__property2__commands__init[]13' },
      { key: 'config__services__property2__commands__init[]14' },
      { key: 'config__services__property2__commands__init[]15' },
      { key: 'config__services__property2__commands__init[]16' },
      { key: 'config__services__property2__commands__init[]17' },
      { key: 'config__services__property2__commands__init[]18' },
      { key: 'config__services__property2__commands__init[]19' },
      { key: 'config__services__property2__commands__init[]20' },
      { key: 'config__services__property2__commands__init[]21' },
      { key: 'config__services__property2__commands__init[]22' },
      { key: 'config__services__property2__commands__init[]23' },
      { key: 'config__services__property2__commands__init[]24' },
      { key: 'config__services__property2__commands__init[]25' },
      { key: 'config__services__property2__commands__init[]26' },
      { key: 'config__services__property2__commands__init[]27' },
      { key: 'config__services__property2__commands__init[]28' },
      { key: 'config__services__property2__commands__init[]29' },
      { key: 'config__services__property2__commands__init[]30' },
      { key: 'config__services__property2__commands__init[]31' },
      { key: 'config__services__property2__commands__init[]32' },
      { key: 'config__services__property2__commands__init[]33' },
      { key: 'config__services__property2__commands__init[]34' },
      { key: 'config__services__property2__commands__init[]35' },
      { key: 'config__services__property2__commands__init[]36' },
      { key: 'config__services__property2__commands__init[]37' },
      { key: 'config__services__property2__commands__init[]38' },
      { key: 'config__services__property2__commands__init[]39' },
      { key: 'config__services__property2__commands__init[]40' },
      { key: 'config__services__property2__commands__init[]41' },
      { key: 'config__services__property2__commands__init[]42' },
      { key: 'config__services__property2__commands__init[]43' },
      { key: 'config__services__property2__commands__init[]44' },
      { key: 'config__services__property2__commands__init[]45' },
      { key: 'config__services__property2__commands__update[]0' },
      { key: 'config__services__property2__commands__update[]1' },
      { key: 'config__services__property2__commands__update[]2' },
      { key: 'config__services__property2__commands__update[]3' },
      { key: 'config__services__property2__commands__update[]4' },
      { key: 'config__services__property2__commands__update[]5' },
      { key: 'config__services__property2__commands__update[]6' },
      { key: 'config__services__property2__commands__update[]7' },
      { key: 'config__services__property2__commands__update[]8' },
      { key: 'config__services__property2__commands__update[]9' },
      { key: 'config__services__property2__commands__update[]10' },
      { key: 'config__services__property2__commands__update[]11' },
      { key: 'config__services__property2__commands__update[]12' },
      { key: 'config__services__property2__commands__update[]13' },
      { key: 'config__services__property2__commands__update[]14' },
      { key: 'config__services__property2__commands__update[]15' },
      { key: 'config__services__property2__commands__update[]16' },
      { key: 'config__services__property2__commands__update[]17' },
      { key: 'config__services__property2__commands__update[]18' },
      { key: 'config__services__property2__commands__update[]19' },
      { key: 'config__services__property2__commands__update[]20' },
      { key: 'config__services__property2__commands__update[]21' },
      { key: 'config__services__property2__commands__update[]22' },
      { key: 'config__services__property2__commands__update[]23' },
      { key: 'config__services__property2__commands__update[]24' },
      { key: 'config__services__property2__commands__update[]25' },
      { key: 'config__services__property2__commands__update[]26' },
      { key: 'config__services__property2__commands__update[]27' },
      { key: 'config__services__property2__commands__update[]28' },
      { key: 'config__services__property2__commands__update[]29' },
      { key: 'config__services__property2__commands__update[]30' },
      { key: 'config__services__property2__commands__update[]31' },
      { key: 'config__services__property2__commands__update[]32' },
      { key: 'config__services__property2__commands__update[]33' },
      { key: 'config__services__property2__commands__update[]34' },
      { key: 'config__services__property2__commands__update[]35' },
      { key: 'config__services__property2__commands__update[]36' },
      { key: 'config__services__property2__commands__update[]37' },
      { key: 'config__services__property2__commands__update[]38' },
      { key: 'config__services__property2__commands__update[]39' },
      { key: 'config__services__property2__commands__update[]40' },
      { key: 'config__services__property2__commands__update[]41' },
      { key: 'config__services__property2__commands__update[]42' },
      { key: 'config__services__property2__commands__update[]43' },
      { key: 'config__services__property2__commands__update[]44' },
      { key: 'config__services__property2__commands__update[]45' },
      { key: 'config__services__property2__commands__update[]46' },
      { key: 'config__services__property2__commands__update[]47' },
      { key: 'config__services__property2__commands__update[]48' },
      { key: 'config__services__property2__commands__update[]49' },
      { key: 'config__services__property2__commands__update[]50' },
      { key: 'config__services__property2__commands__update[]51' },
      { key: 'config__services__property2__commands__update[]52' },
      { key: 'config__services__property2__commands__update[]53' },
      { key: 'config__services__property2__commands__update[]54' },
      { key: 'config__services__property2__commands__update[]55' },
      { key: 'config__services__property2__commands__update[]56' },
      { key: 'config__services__property2__commands__update[]57' },
      { key: 'config__services__property2__commands__update[]58' },
      { key: 'config__services__property2__commands__update[]59' },
      { key: 'config__services__property2__commands__update[]60' },
      { key: 'config__services__property2__commands__update[]61' },
      { key: 'config__services__property2__commands__update[]62' },
      { key: 'config__services__property2__commands__update[]63' },
      { key: 'config__services__property2__commands__update[]64' },
      { key: 'config__services__property2__commands__update[]65' },
      { key: 'config__services__property2__commands__update[]66' },
      { key: 'config__services__property2__commands__update[]67' },
      { key: 'config__services__property2__commands__update[]68' },
      { key: 'config__services__property2__commands__update[]69' },
      { key: 'config__services__property2__commands__update[]70' },
      { key: 'config__services__property2__commands__update[]71' },
      { key: 'config__services__property2__commands__update[]72' },
      { key: 'config__services__property2__commands__update[]73' },
      { key: 'config__services__property2__commands__update[]74' },
      { key: 'config__services__property2__commands__update[]75' },
      { key: 'config__services__property2__commands__build[]0' },
      { key: 'config__services__property2__commands__build[]1' },
      { key: 'config__services__property2__commands__build[]2' },
      { key: 'config__services__property2__commands__build[]3' },
      { key: 'config__services__property2__commands__build[]4' },
      { key: 'config__services__property2__commands__build[]5' },
      { key: 'config__services__property2__commands__build[]6' },
      { key: 'config__services__property2__commands__build[]7' },
      { key: 'config__services__property2__commands__build[]8' },
      { key: 'config__services__property2__commands__build[]9' },
      { key: 'config__services__property2__commands__build[]10' },
      { key: 'config__services__property2__commands__build[]11' },
      { key: 'config__services__property2__commands__build[]12' },
      { key: 'config__services__property2__commands__build[]13' },
      { key: 'config__services__property2__commands__build[]14' },
      { key: 'config__services__property2__commands__build[]15' },
      { key: 'config__services__property2__commands__build[]16' },
      { key: 'config__services__property2__commands__build[]17' },
      { key: 'config__services__property2__commands__build[]18' },
      { key: 'config__services__property2__commands__build[]19' },
      { key: 'config__services__property2__commands__build[]20' },
      { key: 'config__services__property2__commands__build[]21' },
      { key: 'config__services__property2__commands__build[]22' },
      { key: 'config__services__property2__commands__build[]23' },
      { key: 'config__services__property2__commands__build[]24' },
      { key: 'config__services__property2__commands__build[]25' },
      { key: 'config__services__property2__commands__build[]26' },
      { key: 'config__services__property2__commands__build[]27' },
      { key: 'config__services__property2__commands__build[]28' },
      { key: 'config__services__property2__commands__build[]29' },
      { key: 'config__services__property2__commands__build[]30' },
      { key: 'config__services__property2__commands__build[]31' },
      { key: 'config__services__property2__commands__build[]32' },
      { key: 'config__services__property2__commands__build[]33' },
      { key: 'config__services__property2__commands__build[]34' },
      { key: 'config__services__property2__commands__build[]35' },
      { key: 'config__services__property2__commands__build[]36' },
      { key: 'config__services__property2__commands__ready[]0' },
      { key: 'config__services__property2__commands__ready[]1' },
      { key: 'config__services__property2__commands__ready[]2' },
      { key: 'config__services__property2__commands__ready[]3' },
      { key: 'config__services__property2__commands__ready[]4' },
      { key: 'config__services__property2__commands__ready[]5' },
      { key: 'config__services__property2__commands__online[]0' },
      { key: 'config__services__property2__commands__online[]1' },
      { key: 'config__services__property2__commands__online[]2' },
      { key: 'config__services__property2__commands__online[]3' },
      { key: 'config__services__property2__commands__online[]4' },
      { key: 'config__services__property2__commands__online[]5' },
      { key: 'config__services__property2__commands__online[]6' },
      { key: 'config__services__property2__commands__online[]7' },
      { key: 'config__services__property2__commands__online[]8' },
      { key: 'config__services__property2__commands__online[]9' },
      { key: 'config__services__property2__commands__online[]10' },
      { key: 'config__services__property2__commands__online[]11' },
      { key: 'config__services__property2__commands__online[]12' },
      { key: 'config__services__property2__commands__online[]13' },
      { key: 'config__services__property2__commands__online[]14' },
      { key: 'config__services__property2__commands__online[]15' },
      { key: 'config__services__property2__commands__online[]16' },
      { key: 'config__services__property2__commands__online[]17' },
      { key: 'config__services__property2__commands__online[]18' },
      { key: 'config__services__property2__commands__online[]19' },
      { key: 'config__services__property2__commands__online[]20' },
      { key: 'config__services__property2__commands__online[]21' },
      { key: 'config__services__property2__commands__online[]22' },
      { key: 'config__services__property2__commands__online[]23' },
      { key: 'config__services__property2__commands__online[]24' },
      { key: 'config__services__property2__commands__start[]0' },
      { key: 'config__services__property2__commands__start[]1' },
      { key: 'config__services__property2__commands__start[]2' },
      { key: 'config__services__property2__commands__start[]3' },
      { key: 'config__services__property2__commands__start[]4' },
      { key: 'config__services__property2__commands__start[]5' },
      { key: 'config__services__property2__commands__start[]6' },
      { key: 'config__services__property2__commands__start[]7' },
      { key: 'config__services__property2__commands__start[]8' },
      { key: 'config__services__property2__commands__start[]9' },
      { key: 'config__services__property2__commands__start[]10' },
      { key: 'config__services__property2__commands__start[]11' },
      { key: 'config__services__property2__commands__start[]12' },
      { key: 'config__services__property2__commands__start[]13' },
      { key: 'config__services__property2__commands__start[]14' },
      { key: 'config__services__property2__commands__start[]15' },
      { key: 'config__services__property2__commands__start[]16' },
      { key: 'config__services__property2__commands__start[]17' },
      { key: 'config__services__property2__commands__start[]18' },
      { key: 'config__services__property2__commands__start[]19' },
      { key: 'config__services__property2__commands__start[]20' },
      { key: 'config__services__property2__commands__start[]21' },
      { key: 'config__services__property2__commands__clone[]0' },
      { key: 'config__services__property2__commands__clone[]1' },
      { key: 'config__services__property2__commands__clone[]2' },
      { key: 'config__services__property2__commands__clone[]3' },
      { key: 'config__services__property2__commands__clone[]4' },
      { key: 'config__services__property2__commands__clone[]5' },
      { key: 'config__services__property2__commands__clone[]6' },
      { key: 'config__services__property2__commands__clone[]7' },
      { key: 'config__services__property2__commands__clone[]8' },
      { key: 'config__services__property2__commands__clone[]9' },
      { key: 'config__services__property2__commands__clone[]10' },
      { key: 'config__services__property2__commands__clone[]11' },
      { key: 'config__services__property2__commands__clone[]12' },
      { key: 'config__services__property2__commands__clone[]13' },
      { key: 'config__services__property2__commands__clone[]14' },
      { key: 'config__services__property2__commands__clone[]15' },
      { key: 'config__services__property2__commands__clone[]16' },
      { key: 'config__services__property2__commands__clone[]17' },
      { key: 'config__services__property2__commands__clone[]18' },
      { key: 'config__services__property2__commands__clone[]19' },
      { key: 'config__services__property2__commands__clone[]20' },
      { key: 'config__services__property2__commands__clone[]21' },
      { key: 'config__services__property2__commands__clone[]22' },
      { key: 'config__services__property2__commands__clone[]23' },
      { key: 'config__services__property2__commands__clone[]24' },
      { key: 'config__services__property2__commands__clone[]25' },
      { key: 'config__services__property2__commands__clone[]26' },
      { key: 'config__services__property2__commands__clone[]27' },
      { key: 'config__services__property2__commands__clone[]28' },
      { key: 'config__services__property2__commands__clone[]29' },
      { key: 'config__services__property2__commands__clone[]30' },
      { key: 'config__services__property2__commands__clone[]31' },
      { key: 'config__services__property2__commands__clone[]32' },
      { key: 'config__services__property2__commands__clone[]33' },
      { key: 'config__services__property2__commands__clone[]34' },
      { key: 'config__services__property2__commands__clone[]35' },
      { key: 'config__services__property2__commands__clone[]36' },
      { key: 'config__services__property2__commands__clone[]37' },
      { key: 'config__services__property2__commands__clone[]38' },
      { key: 'config__services__property2__commands__clone[]39' },
      { key: 'config__services__property2__commands__clone[]40' },
      { key: 'config__services__property2__commands__clone[]41' },
      { key: 'config__services__property2__commands__clone[]42' },
      { key: 'config__services__property2__commands__clone[]43' },
      { key: 'config__services__property2__commands__clone[]44' },
      { key: 'config__services__property2__commands__clone[]45' },
      { key: 'config__services__property2__commands__clone[]46' },
      { key: 'config__services__property2__commands__clone[]47' },
      { key: 'config__services__property2__commands__clone[]48' },
      { key: 'config__services__property2__commands__clone[]49' },
      { key: 'config__services__property2__commands__clone[]50' },
      { key: 'config__services__property2__commands__clone[]51' },
      { key: 'config__services__property2__commands__clone[]52' },
      { key: 'config__services__property2__commands__clone[]53' },
      { key: 'config__services__property2__commands__clone[]54' },
      { key: 'config__services__property2__commands__clone[]55' },
      { key: 'config__services__property2__commands__clone[]56' },
      { key: 'config__services__property2__commands__clone[]57' },
      { key: 'config__services__property2__commands__clone[]58' },
      { key: 'config__services__property2__commands__clone[]59' },
      { key: 'config__services__property2__default' },
      { key: 'config__services__property2__depends[]0' },
      { key: 'config__services__property2__depends[]1' },
      { key: 'config__services__property2__depends[]2' },
      { key: 'config__services__property2__depends[]3' },
      { key: 'config__services__property2__depends[]4' },
      { key: 'config__services__property2__domain' },
      { key: 'config__services__property2__expose' },
      { key: 'config__services__property2__http' },
      { key: 'config__services__property2__https' },
      { key: 'config__services__property2__image' },
      { key: 'config__services__property2__subpath' },
      { key: 'config__services__property2__subpath_map' },
      { key: 'config__services__property2__visualdiffs[]aliases[]0' },
      { key: 'config__services__property2__visualdiffs[]aliases[]1' },
      { key: 'config__services__property2__visualdiffs[]aliases[]2' },
      { key: 'config__services__property2__visualdiffs[]aliases[]3' },
      { key: 'config__services__property2__visualdiffs[]aliases[]4' },
      { key: 'config__services__property2__visualdiffs[]aliases[]5' },
      { key: 'config__services__property2__visualdiffs[]aliases[]6' },
      { key: 'config__services__property2__visualdiffs[]aliases[]7' },
      { key: 'config__services__property2__visualdiffs[]fullPage' },
      { key: 'config__services__property2__visualdiffs[]timeout' },
      { key: 'config__services__property2__visualdiffs[]url' },
      { key: 'config__services__property2__visualdiffs[]waitUntil[]0' },
      { key: 'default_service' },
      { key: 'expires', type: 'datetime' },
      { key: 'failed' },
      { key: 'hits', type: 'integer' },
      { key: 'id' },
      { key: 'job' },
      { key: 'lasthit', type: 'datetime' },
      { key: 'locked', type: 'boolean' },
      { key: 'mail[]0' },
      { key: 'mail[]1' },
      { key: 'mail[]2' },
      { key: 'mail[]3' },
      { key: 'mail[]4' },
      { key: 'mail[]5' },
      { key: 'mail[]6' },
      { key: 'mail[]7' },
      { key: 'mail[]8' },
      { key: 'mail[]9' },
      { key: 'mail[]10' },
      { key: 'mail[]11' },
      { key: 'mail[]12' },
      { key: 'mail[]13' },
      { key: 'mail[]14' },
      { key: 'mail[]15' },
      { key: 'mail[]16' },
      { key: 'mail[]17' },
      { key: 'mail[]18' },
      { key: 'mail[]19' },
      { key: 'mail[]20' },
      { key: 'mail[]21' },
      { key: 'mail[]22' },
      { key: 'mail[]23' },
      { key: 'name' },
      { key: 'orphaned' },
      { key: 'preview' },
      { key: 'project' },
      { key: 'provider' },
      { key: 'provider_comment', type: 'integer' },
      { key: 'provider_id' },
      { key: 'provider_label' },
      { key: 'provider_link' },
      { key: 'provider_link_sha' },
      { key: 'provider_type' },
      { key: 'repo' },
      { key: 'services[]0' },
      { key: 'services[]1' },
      { key: 'services[]2' },
      { key: 'services[]3' },
      { key: 'services[]4' },
      { key: 'services[]5' },
      { key: 'services[]6' },
      { key: 'services[]7' },
      { key: 'services[]8' },
      { key: 'services[]9' },
      { key: 'services[]10' },
      { key: 'services[]11' },
      { key: 'services[]12' },
      { key: 'services[]13' },
      { key: 'services[]14' },
      { key: 'services[]15' },
      { key: 'services[]16' },
      { key: 'services[]17' },
      { key: 'services[]18' },
      { key: 'services[]19' },
      { key: 'services[]20' },
      { key: 'services[]21' },
      { key: 'services[]22' },
      { key: 'services[]23' },
      { key: 'ref' },
      { key: 'sha' },
      { key: 'size', type: 'integer' },
      { key: 'stale', type: 'boolean' },
      { key: 'state' },
      { key: 'suspended' },
      { key: 'type' },
      { key: 'updatedAt', type: 'datetime' },
      { key: 'url' },
      { key: 'urls[]0' },
      { key: 'urls[]1' },
      { key: 'urls[]2' },
      { key: 'urls[]3' },
      { key: 'urls[]4' },
      { key: 'urls[]5' },
      { key: 'urls[]6' },
      { key: 'urls[]7' },
      { key: 'urls[]8' },
      { key: 'urls[]9' },
      { key: 'urls[]10' },
      { key: 'urls[]11' },
      { key: 'urls[]12' },
      { key: 'urls[]13' },
      { key: 'urls[]14' },
      { key: 'urls[]15' },
      { key: 'urls[]16' },
      { key: 'urls[]17' },
      { key: 'urls[]18' },
      { key: 'urls[]19' },
      { key: 'urls[]20' },
      { key: 'urls[]21' },
      { key: 'urls[]22' },
      { key: 'urls[]23' },
      { key: 'urls[]24' },
      { key: 'urls[]25' },
      { key: 'urls[]26' },
      { key: 'urls[]27' },
      { key: 'urls[]28' },
      { key: 'urls[]29' },
      { key: 'urls[]30' },
      { key: 'urls[]31' },
      { key: 'urls[]32' },
      { key: 'urls[]33' },
      { key: 'urls[]34' },
      { key: 'urls[]35' },
      { key: 'urls[]36' },
      { key: 'urls[]37' },
      { key: 'urls[]38' },
      { key: 'urls[]39' },
      { key: 'urls[]40' },
      { key: 'urls[]41' },
      { key: 'urls[]42' },
      { key: 'urls[]43' },
      { key: 'urls[]44' },
      { key: 'urls[]45' },
      { key: 'urls[]46' },
      { key: 'urls[]47' },
      { key: 'urls[]48' },
      { key: 'urls[]49' },
      { key: 'urls[]50' },
      { key: 'urls[]51' },
      { key: 'urls[]52' },
      { key: 'urls[]53' },
      { key: 'urls[]54' },
      { key: 'urls[]55' },
      { key: 'urls[]56' },
      { key: 'visualdiffs', type: 'boolean' },
    ],
  },
  key: 'find_preview',
  noun: 'Preview',
  display: {
    label: 'Find a Preview',
    description: 'Find a Tugboat Preview by Preview ID',
    hidden: false,
    important: false,
  },
};
