module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/previews/{{bundle.inputData.preview}}/rebuild',
      method: 'POST',
      params: {},
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: {
        children: '{{bundle.inputData.children}}',
        force: '{{bundle.inputData.force}}',
      },
      removeMissingValuesFrom: { body: true },
    },
    inputFields: [
      {
        key: 'project',
        label: 'Project',
        type: 'string',
        dynamic: 'list_projects.project.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'repo',
        label: 'Repository',
        type: 'string',
        dynamic: 'list_repos.repo.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'preview',
        label: 'Preview',
        type: 'string',
        dynamic: 'list_previews.preview.name',
        search: 'find_base_previews.preview',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'children',
        label: 'Rebuild child previews',
        type: 'boolean',
        helpText: 'Whether to rebuild any child Previews when done rebuilding.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'force',
        label: 'Force',
        type: 'boolean',
        helpText:
          'Force the Preview to rebuild if it is a Base Preview to other Previews.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      progress: 0,
      key: '5e62533313ecdf451f3ca42b',
      target: 'previews',
      action: 'rebuild',
      object: '60a6645d757146fcdc92e775',
      args: {
        preview: '60a6645d757146fcdc92e775',
        force: true,
        children: true,
      },
      createdAt: '2021-05-25T17:42:50.269Z',
      updatedAt: '2021-05-25T17:42:50.269Z',
      type: 'job',
      job: '60ad371a3e5c6470819d1c0a',
      id: '60ad371a3e5c6470819d1c0a',
      project: '5fc6717502f60b6e8ad324ec',
      repo: '60a6603dcde7205bd76bfc27',
      preview: '60a6645d757146fcdc92e775',
    },
    outputFields: [
      { key: 'progress', type: 'integer' },
      { key: 'key' },
      { key: 'target' },
      { key: 'action' },
      { key: 'object' },
      { key: 'args__preview' },
      { key: 'args__force', type: 'boolean' },
      { key: 'createdAt' },
      { key: 'updatedAt' },
      { key: 'type' },
      { key: 'job' },
      { key: 'id' },
      { key: 'project' },
      { key: 'repo' },
      { key: 'preview' },
      { key: 'args__children', type: 'boolean' },
    ],
  },
  key: 'rebuild_preview',
  noun: 'Job',
  display: {
    label: 'Rebuild a Preview',
    description: 'Rebuild a Preview',
    hidden: false,
    important: false,
  },
};
