module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/previews/{{bundle.inputData.preview}}/refresh',
      method: 'POST',
      params: {},
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: {
        children: '{{bundle.inputData.children}}',
        force: '{{bundle.inputData.force}}',
      },
      removeMissingValuesFrom: { body: true },
    },
    inputFields: [
      {
        key: 'project',
        label: 'Project',
        type: 'string',
        dynamic: 'list_projects.project.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'repo',
        label: 'Repository',
        type: 'string',
        dynamic: 'list_repos.repo.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'preview',
        label: 'Preview',
        type: 'string',
        dynamic: 'list_previews.preview.name',
        search: 'find_base_previews.preview',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'children',
        label: 'Rebuild child previews',
        type: 'boolean',
        helpText: 'Whether to rebuild any child Previews when done refreshing.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'force',
        label: 'Force',
        type: 'boolean',
        helpText:
          'Force the Preview to refresh even if it is a state that would otherwise prevent refreshing.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      progress: 0,
      key: '5e62533313ecdf451f3ca42b',
      target: 'previews',
      action: 'refresh',
      object: '60a6645d757146fcdc92e775',
      args: {
        preview: '60a6645d757146fcdc92e775',
        children: true,
        force: true,
      },
      createdAt: '2021-05-25T17:59:25.968Z',
      updatedAt: '2021-05-25T17:59:25.968Z',
      type: 'job',
      job: '60ad3afd3e5c64f09b9d210d',
      id: '60ad3afd3e5c64f09b9d210d',
      project: '5fc6717502f60b6e8ad324ec',
      repo: '60a6603dcde7205bd76bfc27',
      preview: '60a6645d757146fcdc92e775',
    },
    outputFields: [
      { key: 'progress', type: 'integer' },
      { key: 'key' },
      { key: 'target' },
      { key: 'action' },
      { key: 'object' },
      { key: 'args__preview' },
      { key: 'args__children', type: 'boolean' },
      { key: 'args__force', type: 'boolean' },
      { key: 'createdAt', type: 'datetime' },
      { key: 'updatedAt', type: 'datetime' },
      { key: 'type' },
      { key: 'job' },
      { key: 'id' },
      { key: 'project' },
      { key: 'repo' },
      { key: 'preview' },
    ],
  },
  key: 'refresh_preview',
  noun: 'Preview',
  display: {
    label: 'Refresh a Preview',
    description: 'Refresh the data on a Preview.',
    hidden: false,
    important: true,
  },
};
