module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/previews/{{bundle.inputData.preview}}/suspend',
      method: 'POST',
      params: {},
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: {},
      removeMissingValuesFrom: {},
    },
    inputFields: [
      {
        key: 'project',
        label: 'Project',
        type: 'string',
        dynamic: 'list_projects.project.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'repo',
        label: 'Repository',
        type: 'string',
        dynamic: 'list_repos.repo.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'preview',
        label: 'Preview',
        type: 'string',
        dynamic: 'list_previews.preview.name',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      progress: 0,
      key: '60ad430acde7205b8f6f2138',
      target: 'previews',
      action: 'suspend',
      object: '60af197dcde7200c7d708cc7',
      args: { preview: '60af197dcde7200c7d708cc7', force: false },
      createdAt: '2021-05-27T12:11:55.797Z',
      updatedAt: '2021-05-27T12:11:55.797Z',
      type: 'job',
      job: '60af8c8b3e5c6419b09ed2bc',
      id: '60af8c8b3e5c6419b09ed2bc',
      project: '5fc6717502f60b6e8ad324ec',
      repo: '60ad4392cde720fae86f213b',
      preview: '60af197dcde7200c7d708cc7',
    },
    outputFields: [
      { key: 'progress', type: 'integer' },
      { key: 'key' },
      { key: 'target' },
      { key: 'action' },
      { key: 'object' },
      { key: 'args__preview' },
      { key: 'args__force' },
      { key: 'createdAt', type: 'datetime' },
      { key: 'updatedAt', type: 'datetime' },
      { key: 'type' },
      { key: 'job' },
      { key: 'id' },
      { key: 'project' },
      { key: 'repo' },
      { key: 'preview' },
    ],
  },
  key: 'suspend_preview',
  noun: 'Job',
  display: {
    label: 'Suspend a Preview',
    description: 'Suspends a Tugboat Preview',
    hidden: false,
    important: false,
  },
};
