const getInputFields = (z, bundle) => {
  if (bundle.inputData.anchor) {
    return {
      key: 'anchor_type',
      label: 'Anchor Type',
      helpText:
        'When anchor is true, this defines how the preview is used as a default Base Preview',
      default: 'repo',
      choices: [
        {
          label:
            'Automatically use this Preview as a Base Preview for all new Previews built for the Repository',
          value: 'repo',
        },
        {
          label:
            'Automatically use this Preview as a Base Preview for new pull request Previews that merge into the branch used to create this Preview',
          value: 'branch',
        },
      ],
    };
  }
};

module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/previews/{{bundle.inputData.preview}}',
      method: 'PATCH',
      params: {},
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: {
        preview: '{{bundle.inputData.preview}}',
        anchor: '{{bundle.inputData.anchor}}',
        config: '{{bundle.inputData.config}}',
        expires: '{{bundle.inputData.expires}}',
        name: '{{bundle.inputData.name}}',
        locked: '{{bundle.inputData.locked}}',
      },
      removeMissingValuesFrom: { body: true },
    },
    inputFields: [
      {
        key: 'preview',
        label: 'Preview ID',
        type: 'string',
        helpText:
          'Insert the [Tugboat ID](https://docs.tugboat.qa/faq/find-tugboat-ids/#preview-id-in-the-web-interface) of the Preview you\'d like to update. You can also use the Zapier "Find Previews" search action to find the Preview.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        helpText: 'A human-readable label for the Preview.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'anchor',
        label: 'Anchor',
        type: 'boolean',
        helpText:
          'Whether to anchor this Preview to use it as a default Base Preview for the Repository.',
        required: false,
        list: false,
        altersDynamicFields: true,
      },
      getInputFields,
      {
        key: 'config',
        label: 'Custom Tugboat Config',
        type: 'text',
        helpText:
          'An optional Preview configuration to use instead of trying to read config.yml from the git repository.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'expires',
        label: 'Expires',
        type: 'datetime',
        helpText:
          'If set, the Preview will automatically be deleted at this time.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'locked',
        label: 'Lock',
        type: 'boolean',
        helpText: 'Whether to lock the Preview.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      anchor: false,
      anchor_type: 'all',
      base: '5d9b59f952163c73a0508bb5',
      build_begin: '2019-10-07T18:29:55.631Z',
      build_end: '2019-10-07T18:30:18.664Z',
      children: ['5d9b842252163ca8a1508c11'],
      clone: '5d9b842252163ca8a1508c11',
      createdAt: '2019-10-07T18:29:54.123Z',
      config: { services: {} },
      default_service: '5d9b842352163cc294508c15',
      expires: '2019-10-07T18:30:18.664Z',
      failed: 'ready',
      hits: 1234,
      id: '5d9b842252163ca8a1508c11',
      job: '5d9e0a3f7f02ad896974a975',
      lasthit: '2019-10-07T20:09:13.330Z',
      locked: false,
      mail: ['5d9b842d52163c3f95508c26'],
      name: 'string',
      orphaned: '5d9b842252163ca8a1508c11',
      preview: '5d9b842252163ca8a1508c11',
      project: '5d810c19f6f8203d5b65ef01',
      provider: 'bitbucket',
      provider_comment: 12345,
      provider_id: 'string',
      provider_label: 'string',
      provider_link: 'http://example.com',
      provider_link_sha: 'http://example.com',
      provider_ref: {},
      provider_type: 'branch',
      repo: '5d810c19f6f82083ed65ef03',
      services: ['5d9b842352163cc294508c15'],
      ref: 'pr123',
      sha: 'aa5db6479307593d10257ee03256f47f2abfdf8a',
      size: 1921191078,
      stale: false,
      state: 'ready',
      suspended: 'ready',
      type: 'preview',
      updatedAt: '2019-10-07T20:30:11.933Z',
      url: 'https://pr123-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
      urls: [
        'https://pr123-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
        'https://foo-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
        'https://bar-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
      ],
      visualdiffs: false,
    },
    outputFields: [
      { key: 'anchor', type: 'boolean' },
      { key: 'anchor_type' },
      { key: 'base' },
      { key: 'build_begin', type: 'datetime' },
      { key: 'build_end', type: 'datetime' },
      { key: 'children[]0' },
      { key: 'children[]1' },
      { key: 'children[]2' },
      { key: 'children[]3' },
      { key: 'children[]4' },
      { key: 'children[]5' },
      { key: 'children[]6' },
      { key: 'children[]7' },
      { key: 'children[]8' },
      { key: 'children[]9' },
      { key: 'children[]10' },
      { key: 'children[]11' },
      { key: 'children[]12' },
      { key: 'children[]13' },
      { key: 'children[]14' },
      { key: 'children[]15' },
      { key: 'children[]16' },
      { key: 'children[]17' },
      { key: 'children[]18' },
      { key: 'children[]19' },
      { key: 'children[]20' },
      { key: 'children[]21' },
      { key: 'children[]22' },
      { key: 'children[]23' },
      { key: 'clone' },
      { key: 'createdAt', type: 'datetime' },
      { key: 'default_service' },
      { key: 'expires', type: 'datetime' },
      { key: 'failed' },
      { key: 'hits', type: 'integer' },
      { key: 'id' },
      { key: 'job' },
      { key: 'lasthit', type: 'datetime' },
      { key: 'locked', type: 'boolean' },
      { key: 'mail[]0' },
      { key: 'mail[]1' },
      { key: 'mail[]2' },
      { key: 'mail[]3' },
      { key: 'mail[]4' },
      { key: 'mail[]5' },
      { key: 'mail[]6' },
      { key: 'mail[]7' },
      { key: 'mail[]8' },
      { key: 'mail[]9' },
      { key: 'mail[]10' },
      { key: 'mail[]11' },
      { key: 'mail[]12' },
      { key: 'mail[]13' },
      { key: 'mail[]14' },
      { key: 'mail[]15' },
      { key: 'mail[]16' },
      { key: 'mail[]17' },
      { key: 'mail[]18' },
      { key: 'mail[]19' },
      { key: 'mail[]20' },
      { key: 'mail[]21' },
      { key: 'mail[]22' },
      { key: 'mail[]23' },
      { key: 'name' },
      { key: 'orphaned' },
      { key: 'preview' },
      { key: 'project' },
      { key: 'provider' },
      { key: 'provider_comment', type: 'integer' },
      { key: 'provider_id' },
      { key: 'provider_label' },
      { key: 'provider_link' },
      { key: 'provider_link_sha' },
      { key: 'provider_type' },
      { key: 'repo' },
      { key: 'services[]0' },
      { key: 'services[]1' },
      { key: 'services[]2' },
      { key: 'services[]3' },
      { key: 'services[]4' },
      { key: 'services[]5' },
      { key: 'services[]6' },
      { key: 'services[]7' },
      { key: 'services[]8' },
      { key: 'services[]9' },
      { key: 'services[]10' },
      { key: 'services[]11' },
      { key: 'services[]12' },
      { key: 'services[]13' },
      { key: 'services[]14' },
      { key: 'services[]15' },
      { key: 'services[]16' },
      { key: 'services[]17' },
      { key: 'services[]18' },
      { key: 'services[]19' },
      { key: 'services[]20' },
      { key: 'services[]21' },
      { key: 'services[]22' },
      { key: 'services[]23' },
      { key: 'ref' },
      { key: 'sha' },
      { key: 'size', type: 'integer' },
      { key: 'stale', type: 'boolean' },
      { key: 'state' },
      { key: 'suspended' },
      { key: 'type' },
      { key: 'updatedAt', type: 'datetime' },
      { key: 'url' },
      { key: 'urls[]0' },
      { key: 'urls[]1' },
      { key: 'urls[]2' },
      { key: 'urls[]3' },
      { key: 'urls[]4' },
      { key: 'urls[]5' },
      { key: 'urls[]6' },
      { key: 'urls[]7' },
      { key: 'urls[]8' },
      { key: 'urls[]9' },
      { key: 'urls[]10' },
      { key: 'urls[]11' },
      { key: 'urls[]12' },
      { key: 'urls[]13' },
      { key: 'urls[]14' },
      { key: 'urls[]15' },
      { key: 'urls[]16' },
      { key: 'urls[]17' },
      { key: 'urls[]18' },
      { key: 'urls[]19' },
      { key: 'urls[]20' },
      { key: 'urls[]21' },
      { key: 'urls[]22' },
      { key: 'urls[]23' },
      { key: 'urls[]24' },
      { key: 'urls[]25' },
      { key: 'urls[]26' },
      { key: 'urls[]27' },
      { key: 'urls[]28' },
      { key: 'urls[]29' },
      { key: 'urls[]30' },
      { key: 'urls[]31' },
      { key: 'urls[]32' },
      { key: 'urls[]33' },
      { key: 'urls[]34' },
      { key: 'urls[]35' },
      { key: 'urls[]36' },
      { key: 'urls[]37' },
      { key: 'urls[]38' },
      { key: 'urls[]39' },
      { key: 'urls[]40' },
      { key: 'urls[]41' },
      { key: 'urls[]42' },
      { key: 'urls[]43' },
      { key: 'urls[]44' },
      { key: 'urls[]45' },
      { key: 'urls[]46' },
      { key: 'urls[]47' },
      { key: 'urls[]48' },
      { key: 'urls[]49' },
      { key: 'urls[]50' },
      { key: 'urls[]51' },
      { key: 'urls[]52' },
      { key: 'urls[]53' },
      { key: 'urls[]54' },
      { key: 'urls[]55' },
      { key: 'urls[]56' },
      { key: 'visualdiffs', type: 'boolean' },
    ],
  },
  key: 'update_preview',
  noun: 'Preview',
  display: {
    label: 'Update a Preview',
    description: 'Updates a Preview',
    hidden: false,
    important: true,
  },
};
