module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/projects',
      method: 'GET',
      params: {},
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: {},
      removeMissingValuesFrom: {},
    },
    sample: {
      guests: [],
      users: [],
      admins: ['5e62533313ecdf451f3ca42b', '5b02ef783558930001c04d5c'],
      quota: 20,
      memory: 2048,
      build_memory: 2048,
      cpus: 2,
      base: true,
      sleep: 15,
      abandoned: 30,
      email_limit: 20,
      email_expire: 24,
      ip_filters: true,
      lighthouse: true,
      visualdiff: true,
      visualdiff_threshold: true,
      dockerauth: true,
      size: 17299950060,
      name: 'TugboatDemo',
      createdAt: '2020-12-01T16:38:13.301Z',
      updatedAt: '2021-05-25T20:37:47.611Z',
      id: '5fc6717502f60b6e8ad324ec',
      type: 'project',
      project: '5fc6717502f60b6e8ad324ec',
      repos: ['60ad4392cde720fae86f213b'],
    },
    outputFields: [
      { key: 'build_memory', type: 'integer', label: 'Build Memory (MB)' },
      { key: 'cpus', label: 'CPUs', type: 'number' },
      { key: 'createdAt', type: 'datetime' },
      { key: 'domain' },
      { key: 'email_expire', type: 'integer' },
      { key: 'email_limit', type: 'integer' },
      { key: 'id', label: 'Project ID' },
      { key: 'memory', label: 'Memory (MB)', type: 'integer' },
      { key: 'name', label: 'Name' },
      { key: 'project', label: 'Project ID' },
      { key: 'quota', label: 'Quota (GB)', type: 'integer' },
      { key: 'size', label: 'Size in bytes', type: 'integer' },
      { key: 'updatedAt', type: 'datetime' },
    ],
  },
  key: 'list_projects',
  noun: 'Project',
  display: {
    label: 'List Projects',
    description: 'Triggers when new Tugboat Projects are added.',
    hidden: false,
    important: false,
  },
};
