module.exports = {
  operation: {
    perform: {
      url: '{{bundle.authData.api_url}}/v3/repos/{{bundle.inputData.repo}}/previews',
      method: 'GET',
      params: {
        token: '{{bundle.authData.token}}',
        api_url: '{{bundle.authData.api_url}}',
        project: '{{bundle.inputData.project}}',
      },
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.token}}',
      },
      body: {},
      removeMissingValuesFrom: {},
    },
    inputFields: [
      {
        key: 'project',
        type: 'string',
        label: 'Project',
        dynamic: 'list_projects.project.name',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'repo',
        type: 'string',
        label: 'Repository',
        dynamic: 'list_repos.repo.name',
        helpText: 'Choose the repository to list Previews for.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      anchor: false,
      anchor_type: 'all',
      base: '5d9b59f952163c73a0508bb5',
      build_begin: '2019-10-07T18:29:55.631Z',
      build_end: '2019-10-07T18:30:18.664Z',
      children: ['5d9b842252163ca8a1508c11'],
      createdAt: '2019-10-07T18:29:54.123Z',
      default_service: '5d9b842352163cc294508c15',
      hits: 1234,
      id: '5d9b842252163ca8a1508c11',
      lasthit: '2019-10-07T20:09:13.330Z',
      locked: false,
      mail: ['5d9b842d52163c3f95508c26'],
      name: 'string',
      preview: '5d9b842252163ca8a1508c11',
      project: '5d810c19f6f8203d5b65ef01',
      provider: 'bitbucket',
      provider_id: 'string',
      provider_label: 'string',
      provider_link: 'http://example.com',
      provider_link_sha: 'http://example.com',
      provider_ref: {},
      provider_type: 'branch',
      repo: '5d810c19f6f82083ed65ef03',
      services: ['5d9b842352163cc294508c15'],
      ref: 'pr123',
      sha: 'aa5db6479307593d10257ee03256f47f2abfdf8a',
      size: 1921191078,
      stale: false,
      state: 'ready',
      type: 'preview',
      updatedAt: '2019-10-07T20:30:11.933Z',
      url: 'https://pr123-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
      urls: [
        'https://pr123-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
        'https://foo-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
        'https://bar-oxfkwf6z6cqr91cdorjwwzwuur9jujvr.tugboat.qa',
      ],
      visualdiffs: false,
    },
    outputFields: [
      { key: 'anchor', type: 'boolean' },
      { key: 'anchor_type', label: 'Base Preview Type' },
      { key: 'base', label: 'Base Preview ID' },
      { key: 'build_begin', type: 'datetime' },
      { key: 'build_end', type: 'datetime' },
      { key: 'createdAt', type: 'datetime' },
      { key: 'default_service' },
      { key: 'hits', type: 'integer' },
      { key: 'id', label: 'Preview ID', type: 'string' },
      { key: 'lasthit', type: 'datetime' },
      { key: 'locked', type: 'boolean', label: 'Locked' },
      { key: 'name', label: 'Name' },
      { key: 'orphaned', type: 'string' },
      { key: 'preview', label: 'Preview ID' },
      { key: 'project', label: 'Project ID' },
      { key: 'provider', label: 'Git provider', type: 'string' },
      { key: 'provider_id' },
      { key: 'provider_label' },
      { key: 'provider_link' },
      { key: 'provider_link_sha' },
      { key: 'provider_type' },
      { key: 'repo', label: 'Repo ID' },
      { key: 'ref', label: 'Git ref' },
      { key: 'sha', label: 'Git sha' },
      { key: 'size', label: 'Size (bytes)', type: 'integer' },
      { key: 'stale', label: 'Stale', type: 'boolean' },
      { key: 'state', label: 'State' },
      { key: 'type', label: 'Preview Type', type: 'string' },
      { key: 'updatedAt', type: 'datetime' },
      { key: 'url', label: 'Default URL' },
      { key: 'urls[]0' },
      { key: 'urls[]1' },
      { key: 'urls[]2' },
      { key: 'urls[]3' },
      { key: 'urls[]4' },
      { key: 'urls[]5' },
      { key: 'urls[]6' },
      { key: 'urls[]7' },
      { key: 'urls[]8' },
      { key: 'urls[]9' },
      { key: 'urls[]10' },
      { key: 'urls[]11' },
      { key: 'urls[]12' },
      { key: 'urls[]13' },
      { key: 'urls[]14' },
      { key: 'urls[]15' },
      { key: 'urls[]16' },
      { key: 'urls[]17' },
      { key: 'urls[]18' },
      { key: 'urls[]19' },
      { key: 'urls[]20' },
      { key: 'urls[]21' },
      { key: 'urls[]22' },
      { key: 'urls[]23' },
      { key: 'urls[]24' },
      { key: 'urls[]25' },
      { key: 'urls[]26' },
      { key: 'urls[]27' },
      { key: 'urls[]28' },
      { key: 'urls[]29' },
      { key: 'urls[]30' },
      { key: 'urls[]31' },
      { key: 'urls[]32' },
      { key: 'urls[]33' },
      { key: 'urls[]34' },
      { key: 'urls[]35' },
      { key: 'urls[]36' },
      { key: 'urls[]37' },
      { key: 'urls[]38' },
      { key: 'urls[]39' },
      { key: 'urls[]40' },
      { key: 'urls[]41' },
      { key: 'urls[]42' },
      { key: 'urls[]43' },
      { key: 'urls[]44' },
      { key: 'urls[]45' },
      { key: 'urls[]46' },
      { key: 'urls[]47' },
      { key: 'urls[]48' },
      { key: 'urls[]49' },
      { key: 'urls[]50' },
      { key: 'urls[]51' },
      { key: 'urls[]52' },
      { key: 'urls[]53' },
      { key: 'urls[]54' },
      { key: 'urls[]55' },
      { key: 'urls[]56' },
      { key: 'visualdiffs', type: 'boolean' },
    ],
  },
  key: 'list_previews',
  noun: 'Preview',
  display: {
    label: 'List Repository Previews',
    description: 'Triggers when new Previews are created.',
    hidden: false,
    important: false,
  },
};
